language: swift
osx_image: xcode14.0.1
branches:
  only:
    - master

before_install:
  - gem install fastlane --no-document
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone 11"
